import { CategoryReward, RewardType } from '../types';

export interface CardTemplate {
  name: string;
  bank: string;
  network: 'visa' | 'mastercard' | 'amex' | 'discover';
  colorScheme: string;
  annualFee: number;
  baseReward: number;
  baseRewardType: RewardType;
  rewards: Omit<CategoryReward, 'maxSpendPeriod'>[];
  notes: string;
  keywords: string[];
}

export const CARD_DATABASE: CardTemplate[] = [
  {
    name: 'Amex Gold Card',
    bank: 'American Express',
    network: 'amex',
    colorScheme: 'gold',
    annualFee: 325,
    baseReward: 1,
    baseRewardType: 'points',
    rewards: [
      { category: 'dining', rewardRate: 4, rewardType: 'points' },
      { category: 'groceries', rewardRate: 4, rewardType: 'points', maxSpend: 25000 },
      { category: 'travel', rewardRate: 3, rewardType: 'points' },
    ],
    notes: '4x dining & US groceries (up to $25K/yr), 3x flights',
    keywords: ['amex gold', 'american express gold'],
  },
  {
    name: 'Amex Platinum Card',
    bank: 'American Express',
    network: 'amex',
    colorScheme: 'slate',
    annualFee: 695,
    baseReward: 1,
    baseRewardType: 'points',
    rewards: [
      { category: 'travel', rewardRate: 5, rewardType: 'points' },
      { category: 'hotels', rewardRate: 5, rewardType: 'points' },
    ],
    notes: '5x on flights & Amex Travel, $200 hotel credit, lounge access',
    keywords: ['amex platinum', 'american express platinum'],
  },
  {
    name: 'Amex Blue Cash Preferred',
    bank: 'American Express',
    network: 'amex',
    colorScheme: 'indigo',
    annualFee: 95,
    baseReward: 1,
    baseRewardType: 'cashback',
    rewards: [
      { category: 'groceries', rewardRate: 6, rewardType: 'cashback', maxSpend: 6000 },
      { category: 'streaming', rewardRate: 6, rewardType: 'cashback' },
      { category: 'gas', rewardRate: 3, rewardType: 'cashback' },
      { category: 'retail', rewardRate: 3, rewardType: 'cashback' },
    ],
    notes: '6% groceries (up to $6K/yr) & streaming, 3% gas & transit',
    keywords: ['blue cash preferred', 'amex blue cash preferred'],
  },
  {
    name: 'Amex Blue Cash Everyday',
    bank: 'American Express',
    network: 'amex',
    colorScheme: 'sapphire',
    annualFee: 0,
    baseReward: 1,
    baseRewardType: 'cashback',
    rewards: [
      { category: 'groceries', rewardRate: 3, rewardType: 'cashback', maxSpend: 6000 },
      { category: 'online', rewardRate: 3, rewardType: 'cashback', maxSpend: 6000 },
      { category: 'gas', rewardRate: 2, rewardType: 'cashback' },
    ],
    notes: '3% groceries & online shopping (up to $6K each/yr), 2% gas',
    keywords: ['blue cash everyday', 'amex blue cash everyday'],
  },
  {
    name: 'Hilton Honors Amex Card',
    bank: 'American Express',
    network: 'amex',
    colorScheme: 'sapphire',
    annualFee: 0,
    baseReward: 3,
    baseRewardType: 'points',
    rewards: [
      { category: 'hotels', rewardRate: 7, rewardType: 'points' },
      { category: 'dining', rewardRate: 5, rewardType: 'points' },
      { category: 'groceries', rewardRate: 5, rewardType: 'points' },
      { category: 'gas', rewardRate: 5, rewardType: 'points' },
    ],
    notes: '7x Hilton properties, 5x dining/groceries/gas, 3x everywhere else',
    keywords: ['hilton honors amex', 'hilton amex', 'hilton honors card'],
  },
  {
    name: 'Hilton Honors Amex Surpass',
    bank: 'American Express',
    network: 'amex',
    colorScheme: 'gold',
    annualFee: 150,
    baseReward: 3,
    baseRewardType: 'points',
    rewards: [
      { category: 'hotels', rewardRate: 12, rewardType: 'points' },
      { category: 'dining', rewardRate: 6, rewardType: 'points' },
      { category: 'groceries', rewardRate: 6, rewardType: 'points' },
      { category: 'gas', rewardRate: 6, rewardType: 'points' },
    ],
    notes: '12x Hilton, 6x dining/groceries/gas, free weekend night annually',
    keywords: ['hilton surpass', 'hilton honors surpass'],
  },
  {
    name: 'Chase Sapphire Preferred',
    bank: 'Chase',
    network: 'visa',
    colorScheme: 'sapphire',
    annualFee: 95,
    baseReward: 1,
    baseRewardType: 'points',
    rewards: [
      { category: 'dining', rewardRate: 3, rewardType: 'points' },
      { category: 'groceries', rewardRate: 3, rewardType: 'points' },
      { category: 'streaming', rewardRate: 3, rewardType: 'points' },
      { category: 'online', rewardRate: 3, rewardType: 'points' },
      { category: 'travel', rewardRate: 5, rewardType: 'points' },
      { category: 'hotels', rewardRate: 5, rewardType: 'points' },
    ],
    notes: '5x on Chase Travel, 3x dining/streaming/groceries',
    keywords: ['chase sapphire preferred', 'sapphire preferred'],
  },
  {
    name: 'Chase Sapphire Reserve',
    bank: 'Chase',
    network: 'visa',
    colorScheme: 'slate',
    annualFee: 550,
    baseReward: 1,
    baseRewardType: 'points',
    rewards: [
      { category: 'dining', rewardRate: 3, rewardType: 'points' },
      { category: 'travel', rewardRate: 10, rewardType: 'points' },
      { category: 'hotels', rewardRate: 10, rewardType: 'points' },
    ],
    notes: '10x on hotels & car rentals via Chase Travel, 3x dining & travel',
    keywords: ['chase sapphire reserve', 'sapphire reserve', 'csr'],
  },
  {
    name: 'Chase Freedom Unlimited',
    bank: 'Chase',
    network: 'visa',
    colorScheme: 'teal',
    annualFee: 0,
    baseReward: 1.5,
    baseRewardType: 'cashback',
    rewards: [
      { category: 'dining', rewardRate: 3, rewardType: 'cashback' },
      { category: 'pharmacy', rewardRate: 3, rewardType: 'cashback' },
      { category: 'travel', rewardRate: 5, rewardType: 'cashback' },
    ],
    notes: '5% Chase Travel, 3% dining & pharmacy, 1.5% everywhere else',
    keywords: ['chase freedom unlimited', 'freedom unlimited', 'cfu'],
  },
  {
    name: 'Chase Freedom Flex',
    bank: 'Chase',
    network: 'mastercard',
    colorScheme: 'sapphire',
    annualFee: 0,
    baseReward: 1,
    baseRewardType: 'cashback',
    rewards: [
      { category: 'dining', rewardRate: 3, rewardType: 'cashback' },
      { category: 'pharmacy', rewardRate: 3, rewardType: 'cashback' },
      { category: 'travel', rewardRate: 5, rewardType: 'cashback' },
    ],
    notes: '5% rotating categories (quarterly), 5% Chase Travel, 3% dining & pharmacy',
    keywords: ['chase freedom flex', 'freedom flex', 'cff'],
  },
  {
    name: 'Capital One Venture X',
    bank: 'Capital One',
    network: 'visa',
    colorScheme: 'indigo',
    annualFee: 395,
    baseReward: 2,
    baseRewardType: 'miles',
    rewards: [
      { category: 'travel', rewardRate: 10, rewardType: 'miles' },
      { category: 'hotels', rewardRate: 10, rewardType: 'miles' },
    ],
    notes: '10x on hotels & rentals via Capital One Travel, 2x everywhere',
    keywords: ['venture x', 'capital one venture x'],
  },
  {
    name: 'Capital One Venture',
    bank: 'Capital One',
    network: 'visa',
    colorScheme: 'indigo',
    annualFee: 95,
    baseReward: 2,
    baseRewardType: 'miles',
    rewards: [
      { category: 'hotels', rewardRate: 5, rewardType: 'miles' },
      { category: 'travel', rewardRate: 5, rewardType: 'miles' },
    ],
    notes: '5x on hotels & rental cars via Capital One Travel, 2x everywhere',
    keywords: ['capital one venture', 'venture card'],
  },
  {
    name: 'Capital One Quicksilver',
    bank: 'Capital One',
    network: 'mastercard',
    colorScheme: 'emerald',
    annualFee: 0,
    baseReward: 1.5,
    baseRewardType: 'cashback',
    rewards: [],
    notes: '1.5% cash back on everything, no annual fee',
    keywords: ['quicksilver', 'capital one quicksilver'],
  },
  {
    name: 'Citi Double Cash',
    bank: 'Citi',
    network: 'mastercard',
    colorScheme: 'slate',
    annualFee: 0,
    baseReward: 2,
    baseRewardType: 'cashback',
    rewards: [],
    notes: '2% on everything (1% when you buy + 1% when you pay)',
    keywords: ['citi double cash', 'double cash'],
  },
  {
    name: 'Citi Strata Premier',
    bank: 'Citi',
    network: 'mastercard',
    colorScheme: 'sapphire',
    annualFee: 95,
    baseReward: 1,
    baseRewardType: 'points',
    rewards: [
      { category: 'dining', rewardRate: 3, rewardType: 'points' },
      { category: 'groceries', rewardRate: 3, rewardType: 'points' },
      { category: 'gas', rewardRate: 3, rewardType: 'points' },
      { category: 'travel', rewardRate: 3, rewardType: 'points' },
      { category: 'hotels', rewardRate: 10, rewardType: 'points' },
    ],
    notes: '10x hotels, 3x dining/groceries/gas/travel, 1x everywhere',
    keywords: ['citi strata premier', 'strata premier', 'citi premier'],
  },
  {
    name: 'Citi Simplicity',
    bank: 'Citi',
    network: 'mastercard',
    colorScheme: 'slate',
    annualFee: 0,
    baseReward: 0,
    baseRewardType: 'cashback',
    rewards: [],
    notes: 'No rewards — 0% intro APR balance transfer card',
    keywords: ['citi simplicity', 'simplicity card'],
  },
  {
    name: 'Costco Anywhere Visa',
    bank: 'Citi',
    network: 'visa',
    colorScheme: 'sapphire',
    annualFee: 0,
    baseReward: 1,
    baseRewardType: 'cashback',
    rewards: [
      { category: 'gas', rewardRate: 4, rewardType: 'cashback', maxSpend: 7000 },
      { category: 'dining', rewardRate: 3, rewardType: 'cashback' },
      { category: 'travel', rewardRate: 3, rewardType: 'cashback' },
      { category: 'wholesale', rewardRate: 2, rewardType: 'cashback' },
    ],
    notes: '4% gas (up to $7K/yr), 3% dining & travel, 2% Costco, 1% everywhere',
    keywords: ['costco anywhere', 'costco visa', 'citi costco'],
  },
  {
    name: 'Discover it Cash Back',
    bank: 'Discover',
    network: 'discover',
    colorScheme: 'rose',
    annualFee: 0,
    baseReward: 1,
    baseRewardType: 'cashback',
    rewards: [
      { category: 'dining', rewardRate: 5, rewardType: 'cashback' },
      { category: 'gas', rewardRate: 5, rewardType: 'cashback' },
      { category: 'groceries', rewardRate: 5, rewardType: 'cashback' },
      { category: 'wholesale', rewardRate: 5, rewardType: 'cashback' },
    ],
    notes: '5% rotating quarterly categories (update each quarter), 1% everywhere',
    keywords: ['discover it', 'discover cash back'],
  },
  {
    name: 'Verizon Visa Card',
    bank: 'Synchrony',
    network: 'visa',
    colorScheme: 'indigo',
    annualFee: 0,
    baseReward: 1,
    baseRewardType: 'cashback',
    rewards: [
      { category: 'groceries', rewardRate: 4, rewardType: 'cashback' },
      { category: 'dining', rewardRate: 3, rewardType: 'cashback' },
      { category: 'gas', rewardRate: 2, rewardType: 'cashback' },
    ],
    notes: '4% groceries, 3% dining, 2% gas & Verizon purchases',
    keywords: ['verizon visa', 'verizon card'],
  },
  {
    name: 'Wells Fargo Active Cash',
    bank: 'Wells Fargo',
    network: 'visa',
    colorScheme: 'rose',
    annualFee: 0,
    baseReward: 2,
    baseRewardType: 'cashback',
    rewards: [],
    notes: '2% unlimited cash rewards on all purchases',
    keywords: ['wells fargo active cash', 'active cash'],
  },
  {
    name: 'Bank of America Customized Cash',
    bank: 'Bank of America',
    network: 'visa',
    colorScheme: 'rose',
    annualFee: 0,
    baseReward: 1,
    baseRewardType: 'cashback',
    rewards: [
      { category: 'gas', rewardRate: 3, rewardType: 'cashback' },
      { category: 'online', rewardRate: 3, rewardType: 'cashback' },
      { category: 'dining', rewardRate: 2, rewardType: 'cashback' },
      { category: 'groceries', rewardRate: 2, rewardType: 'cashback' },
    ],
    notes: '3% on your choice category, 2% grocery & wholesale, 1% everywhere',
    keywords: ['bank of america customized cash', 'boa customized cash', 'bofa customized'],
  },
  {
    name: 'US Bank Altitude Go',
    bank: 'US Bank',
    network: 'visa',
    colorScheme: 'teal',
    annualFee: 0,
    baseReward: 1,
    baseRewardType: 'points',
    rewards: [
      { category: 'dining', rewardRate: 4, rewardType: 'points' },
      { category: 'groceries', rewardRate: 2, rewardType: 'points' },
      { category: 'gas', rewardRate: 2, rewardType: 'points' },
      { category: 'streaming', rewardRate: 2, rewardType: 'points' },
    ],
    notes: '4x dining (including takeout), 2x groceries/gas/streaming',
    keywords: ['us bank altitude go', 'altitude go'],
  },
  {
    name: 'Robinhood Gold Card',
    bank: 'Robinhood / Coastal Community',
    network: 'mastercard',
    colorScheme: 'emerald',
    annualFee: 0,
    baseReward: 3,
    baseRewardType: 'cashback',
    rewards: [],
    notes: '3% cash back on all purchases (requires Robinhood Gold $5/mo)',
    keywords: ['robinhood gold card', 'robinhood card', 'robinhood'],
  },
  {
    name: 'Apple Card',
    bank: 'Goldman Sachs',
    network: 'mastercard',
    colorScheme: 'slate',
    annualFee: 0,
    baseReward: 1,
    baseRewardType: 'cashback',
    rewards: [
      { category: 'online', rewardRate: 3, rewardType: 'cashback' },
      { category: 'dining', rewardRate: 2, rewardType: 'cashback' },
      { category: 'groceries', rewardRate: 2, rewardType: 'cashback' },
    ],
    notes: '3% Apple & select merchants, 2% Apple Pay purchases, 1% everywhere',
    keywords: ['apple card', 'apple credit card'],
  },
  {
    name: 'Amazon Prime Visa',
    bank: 'Chase',
    network: 'visa',
    colorScheme: 'indigo',
    annualFee: 0,
    baseReward: 1,
    baseRewardType: 'cashback',
    rewards: [
      { category: 'online', rewardRate: 5, rewardType: 'cashback' },
      { category: 'groceries', rewardRate: 5, rewardType: 'cashback' },
      { category: 'dining', rewardRate: 2, rewardType: 'cashback' },
      { category: 'gas', rewardRate: 2, rewardType: 'cashback' },
      { category: 'pharmacy', rewardRate: 2, rewardType: 'cashback' },
    ],
    notes: '5% Amazon & Whole Foods, 2% dining/gas/drugstores (Prime required)',
    keywords: ['amazon prime visa', 'amazon visa', 'amazon rewards'],
  },
  {
    name: 'PayPal Cashback Mastercard',
    bank: 'Synchrony',
    network: 'mastercard',
    colorScheme: 'sapphire',
    annualFee: 0,
    baseReward: 1.5,
    baseRewardType: 'cashback',
    rewards: [
      { category: 'online', rewardRate: 3, rewardType: 'cashback' },
    ],
    notes: '3% PayPal purchases, 1.5% everywhere else',
    keywords: ['paypal cashback', 'paypal mastercard', 'paypal card'],
  },
  {
    name: 'Target RedCard',
    bank: 'TD Bank',
    network: 'mastercard',
    colorScheme: 'rose',
    annualFee: 0,
    baseReward: 1,
    baseRewardType: 'cashback',
    rewards: [
      { category: 'retail', rewardRate: 5, rewardType: 'cashback' },
      { category: 'online', rewardRate: 5, rewardType: 'cashback' },
      { category: 'groceries', rewardRate: 5, rewardType: 'cashback' },
    ],
    notes: '5% off at Target stores and Target.com',
    keywords: ['target redcard', 'target red card', 'target card'],
  },
  {
    name: "Sam's Club Mastercard",
    bank: 'Synchrony',
    network: 'mastercard',
    colorScheme: 'sapphire',
    annualFee: 0,
    baseReward: 1,
    baseRewardType: 'cashback',
    rewards: [
      { category: 'gas', rewardRate: 5, rewardType: 'cashback', maxSpend: 6000 },
      { category: 'dining', rewardRate: 3, rewardType: 'cashback' },
      { category: 'travel', rewardRate: 3, rewardType: 'cashback' },
      { category: 'wholesale', rewardRate: 3, rewardType: 'cashback' },
    ],
    notes: "5% gas (up to $6K/yr), 3% dining & travel, 3% Sam's Club",
    keywords: ["sam's club", 'sams club mastercard', 'sams club card'],
  },
  {
    name: 'Fidelity Rewards Visa',
    bank: 'Elan Financial',
    network: 'visa',
    colorScheme: 'emerald',
    annualFee: 0,
    baseReward: 2,
    baseRewardType: 'cashback',
    rewards: [],
    notes: '2% unlimited cash back deposited into Fidelity account',
    keywords: ['fidelity rewards', 'fidelity visa', 'fidelity card'],
  },
  {
    name: 'SoFi Unlimited Cash Back',
    bank: 'SoFi',
    network: 'mastercard',
    colorScheme: 'teal',
    annualFee: 0,
    baseReward: 2,
    baseRewardType: 'cashback',
    rewards: [],
    notes: '2% everywhere (3% with SoFi direct deposit)',
    keywords: ['sofi unlimited', 'sofi cash back', 'sofi card'],
  },
  {
    name: 'Chase Ink Business Cash',
    bank: 'Chase',
    network: 'visa',
    colorScheme: 'sapphire',
    annualFee: 0,
    baseReward: 1,
    baseRewardType: 'cashback',
    rewards: [
      { category: 'online', rewardRate: 5, rewardType: 'cashback', maxSpend: 25000 },
      { category: 'streaming', rewardRate: 5, rewardType: 'cashback', maxSpend: 25000 },
      { category: 'dining', rewardRate: 2, rewardType: 'cashback' },
      { category: 'gas', rewardRate: 2, rewardType: 'cashback' },
    ],
    notes: '5% office & internet (up to $25K/yr), 2% gas & dining',
    keywords: ['ink business cash', 'chase ink cash', 'ink cash'],
  },
  {
    name: 'Marriott Bonvoy Boundless',
    bank: 'Chase',
    network: 'visa',
    colorScheme: 'gold',
    annualFee: 95,
    baseReward: 2,
    baseRewardType: 'points',
    rewards: [
      { category: 'hotels', rewardRate: 17, rewardType: 'points' },
      { category: 'dining', rewardRate: 3, rewardType: 'points' },
      { category: 'groceries', rewardRate: 3, rewardType: 'points' },
      { category: 'gas', rewardRate: 3, rewardType: 'points' },
    ],
    notes: '17x at Marriott hotels, 3x dining/groceries/gas, free night annually',
    keywords: ['marriott bonvoy boundless', 'marriott bonvoy', 'marriott chase'],
  },
  {
    name: 'World of Hyatt Credit Card',
    bank: 'Chase',
    network: 'visa',
    colorScheme: 'indigo',
    annualFee: 95,
    baseReward: 1,
    baseRewardType: 'points',
    rewards: [
      { category: 'hotels', rewardRate: 9, rewardType: 'points' },
      { category: 'dining', rewardRate: 2, rewardType: 'points' },
      { category: 'travel', rewardRate: 2, rewardType: 'points' },
      { category: 'other', rewardRate: 2, rewardType: 'points' },
    ],
    notes: '9x at Hyatt hotels, 2x dining/travel/fitness, free night annually',
    keywords: ['world of hyatt', 'hyatt credit card', 'hyatt card'],
  },
  {
    name: 'IHG One Rewards Premier',
    bank: 'Chase',
    network: 'mastercard',
    colorScheme: 'teal',
    annualFee: 99,
    baseReward: 3,
    baseRewardType: 'points',
    rewards: [
      { category: 'hotels', rewardRate: 26, rewardType: 'points' },
      { category: 'dining', rewardRate: 5, rewardType: 'points' },
      { category: 'gas', rewardRate: 5, rewardType: 'points' },
      { category: 'groceries', rewardRate: 5, rewardType: 'points' },
    ],
    notes: '26x at IHG hotels, 5x dining/gas/groceries, free night annually',
    keywords: ['ihg one rewards', 'ihg premier', 'ihg card', 'intercontinental'],
  },
  {
    name: 'Wyndham Rewards Earner',
    bank: 'Barclays',
    network: 'visa',
    colorScheme: 'sapphire',
    annualFee: 75,
    baseReward: 1,
    baseRewardType: 'points',
    rewards: [
      { category: 'hotels', rewardRate: 6, rewardType: 'points' },
      { category: 'gas', rewardRate: 5, rewardType: 'points' },
      { category: 'dining', rewardRate: 4, rewardType: 'points' },
    ],
    notes: '6x Wyndham hotels, 5x gas, 4x dining & groceries',
    keywords: ['wyndham rewards', 'wyndham earner', 'wyndham card'],
  },
  {
    name: 'Delta SkyMiles Gold Amex',
    bank: 'American Express',
    network: 'amex',
    colorScheme: 'gold',
    annualFee: 150,
    baseReward: 1,
    baseRewardType: 'miles',
    rewards: [
      { category: 'travel', rewardRate: 3, rewardType: 'miles' },
      { category: 'dining', rewardRate: 2, rewardType: 'miles' },
      { category: 'groceries', rewardRate: 2, rewardType: 'miles' },
    ],
    notes: '3x Delta flights, 2x dining & groceries, free checked bag',
    keywords: ['delta skymiles gold', 'delta gold amex', 'delta amex gold'],
  },
  {
    name: 'United Explorer Card',
    bank: 'Chase',
    network: 'visa',
    colorScheme: 'sapphire',
    annualFee: 95,
    baseReward: 1,
    baseRewardType: 'miles',
    rewards: [
      { category: 'travel', rewardRate: 2, rewardType: 'miles' },
      { category: 'hotels', rewardRate: 2, rewardType: 'miles' },
      { category: 'dining', rewardRate: 2, rewardType: 'miles' },
    ],
    notes: '2x United flights, hotels & dining, free checked bag',
    keywords: ['united explorer', 'united mileageplus explorer', 'united chase'],
  },
  {
    name: 'Southwest Rapid Rewards Plus',
    bank: 'Chase',
    network: 'visa',
    colorScheme: 'rose',
    annualFee: 69,
    baseReward: 1,
    baseRewardType: 'points',
    rewards: [
      { category: 'travel', rewardRate: 2, rewardType: 'points' },
      { category: 'hotels', rewardRate: 2, rewardType: 'points' },
      { category: 'dining', rewardRate: 2, rewardType: 'points' },
      { category: 'streaming', rewardRate: 2, rewardType: 'points' },
    ],
    notes: '2x Southwest purchases, hotels & car rentals, dining & streaming',
    keywords: ['southwest rapid rewards', 'southwest plus', 'southwest card'],
  },
];

export function findCardTemplate(query: string): CardTemplate | null {
  const lower = query.toLowerCase().trim();
  if (!lower) return null;

  // Exact keyword match first
  for (const card of CARD_DATABASE) {
    if (card.keywords.some((kw) => lower.includes(kw) || kw.includes(lower))) {
      return card;
    }
  }

  // Fuzzy: check if card name words appear in query
  for (const card of CARD_DATABASE) {
    const nameWords = card.name.toLowerCase().split(' ').filter((w) => w.length > 3);
    const matches = nameWords.filter((w) => lower.includes(w));
    if (matches.length >= 2) return card;
  }

  return null;
}
